### ISSUE TITLE
Never "git add ...." auto-add

### ISSUE THREAD

**Issue by dereuromark** [spryker/git-hook#5]
This breaks peoples repos, as stuff on a different "list" not added, suddenly gets autoadded and auto-pushed.
That is very dangerous.

It should also not auto-fix, only report
To manually run the fixer is easy enough and can be even suggested in the error message

    Run `console ...` now to fix the fixable errors, fix the rest manually etc.

**Comment by stereomon** [comment]
Disabled in project configuration
