### ISSUE TITLE
Error on required ruleset.xml which isn't present

### ISSUE THREAD

**Issue by timok-at-towa** [spryker/git-hook#54]
https://github.com/spryker/git-hook/blob/efad48ab3458bfdd0d0e3e21c8ecd722d142bbbd/src/GitHook/Command/FileCommand/PreCommit/CodeStyleFixCommand.php#L45

The requirement for the config/ruleset.xml causes an error:  ```ERROR: the "config/ruleset.xml" coding standard is not installed.```

EDIT:
Replacing the mentioned file path with ```--standard=phpcs.xml``` solved the issue without further errors.

**Comment by dereuromark** [comment]
@stereomon Can you check this?
It should first use the root level phpxs.xml file as per our rules first. Only afterwards check legacy location.

Also optionally, maybe it can check first if "composer cs-check" exists to use that instead as it fully wraps it.

**Comment by stereomon** [comment]
That needs to fixed by UX I guess.
