### ISSUE TITLE
use more general shebang for githooks 

### ISSUE THREAD

**Issue by JimPanse2k19** [spryker/git-hook#55]
`#!/usr/bin/php`

forces git to use always /usr/bin/php when running the hooks. But this is not always the install path for php executable, especially if installed locally with managers like homebrew etc ... 

The script will then fail with

./.git/hooks/pre-commit: no such file or directory

which is also misleading since it indicates a missing pre commit script but actually means the missing executable for php

`#!/usr/bin/env php`

might be the better expression since it lets the system find the php executable

**Comment by dereuromark** [comment]
https://github.com/spryker/git-hook/pull/59
